//! Raw libavcodec/libavutil FFI for the NVENC backend, generated by `build.rs`
//! (bindgen). Not for direct use — see [`crate::NvencEncoder`]. Lints silenced:
//! machine-generated code.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
#![allow(clippy::all, clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/av_bindings.rs"));
