//! Raw libx265 FFI, generated by `build.rs` (bindgen). Not for direct use —
//! see [`crate::HevcEncoder`] for the safe wrapper. Lints are silenced wholesale
//! here: this is machine-generated code, not code we maintain by hand.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
#![allow(clippy::all, clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/x265_bindings.rs"));
